# The URL the site will be built for
base_url = "https://gianmiriano.cyou"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{name = "tags"}]

default_language = "en"

# enable theme
theme = "archie-zola"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

highlight_theme = "OneHalfLight"

[extra]
# Put all your custom variables here
# control dark mode: auto | dark | toggle
mode = "toggle"

# subtitle will show under the title in index page
subtitle = "My personal blog"

# if set true, will use external CDN resource to load font and js file
useCDN = false

#favicon = "/icon/favicon.png"

# show in the footer
copyright = "Gianmiriano"

# config your Google Analysis ID
#ga = "XXXX-XXXXX"

# optional: config your i18n entry
[extra.translations]
languages = [{name = "en", url = "/"}]

# config multi-language menu and other text
[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "All posts", url = "/posts", weight = 2 },
    { name = "About", url = "/about", weight = 3 },
    { name = "Tags", url = "/tags", weight = 4 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/cronoimpius"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/gianmiriano"

[[extra.social]]
icon = "gitlab"
name = "GitLab"
url = "https://gitlab.com/cronoimpius"

[[extra.socila]]
icon = "reddit"
name = "Reddit"
url = ""
