# On every push this script is executed
on: push
name: Build and deploy GH Pages
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout master
        #uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          # Provide personal access token
          TOKEN: ${{ secrets.GH_TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Target branch
          PAGES_BRANCH: gh-pages
          
