# On every push this script is executed
on: push
name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout master
        uses: actions/checkout@v3
      - name: my-scanner
        run: /scripts/entrypoint.sh
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          # Provide personal access token
          TOKEN: ${{ secrets.GH_TOKEN }}
          # Target branch
          PAGES_BRANCH: gh-pages

